name: Delete Feed Generator

on:
  workflow_dispatch:
    inputs:
      record_name:
        description: "Record Name"
        required: true

jobs:
  publish_feed_generator:
    runs-on: ubuntu-latest
    name: Delete Feed Generator
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Set GITHUB_ENV
      - name: Delete Feed Generator
        env:
          RECORD_NAME: ${{ inputs.record_name }}
          FEEDGEN_SERVICE_DID: ${{ vars.FEEDGEN_SERVICE_DID }}
          BLUESKY_HANDLE: ${{ vars.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: |
          cd scripts/
          npm install
          echo ${RECORD_NAME}
          yarn deleteFeedGenerator